#!/bin/bash
VIRTME_INTERACTIVE=""
[ "${VIRTME_NO_INTERACTIVE}" != 1 ] && VIRTME_INTERACTIVE="-it"
docker run \
	-v "${PWD}:${PWD}:rw" \
	${VIRTME_PACKETDRILL_PATH:+-v "${VIRTME_PACKETDRILL_PATH}:/opt/packetdrill:rw"} \
	-w "${PWD}" \
	-e "INPUT_TRACE" \
	-e "INPUT_NO_BLOCK" \
	-e "INPUT_RUN_LOOP_CONTINUE" \
	-e "INPUT_BUILD_SKIP" \
	-e "INPUT_BUILD_SKIP_PERF" \
	-e "INPUT_BUILD_SKIP_SELFTESTS" \
	-e "INPUT_BUILD_SKIP_PACKETDRILL" \
	-e "INPUT_RUN_TESTS_ONLY" \
	-e "INPUT_RUN_TESTS_EXCEPT" \
	-e "INPUT_SELFTESTS_DIR" \
	-e "INPUT_SELFTESTS_MPTCP_LIB_EXPECT_ALL_FEATURES" \
	-e "INPUT_PACKETDRILL_NO_SYNC=${VIRTME_PACKETDRILL_PATH:+1}" \
	-e "INPUT_PACKETDRILL_NO_MORE_TOLERANCE=${INPUT_PACKETDRILL_NO_MORE_TOLERANCE:-${VIRTME_PACKETDRILL_PATH:+1}}" \
	-e "INPUT_PACKETDRILL_STABLE=${VIRTME_PACKETDRILL_STABLE:-0}" \
	-e "INPUT_EXPECT_TIMEOUT" \
	-e "VIRTME_ARCH" \
	-e "COMPILER" \
	--privileged \
	--rm \
	${VIRTME_INTERACTIVE} \
	"${DOCKER_VIRTME_NAME:-"mptcp/mptcp-upstream-virtme-docker:latest"}" \
	"${@}"
